# This is a basic workflow to help you get started with Actions

name: Build Native CLI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  NATIVE_VERSION: 1.0.10
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  OSX_LINUX_WINDOWS:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]
        include:
          - os: windows-2019
            script_name: windows
          - os: ubuntu-latest
            script_name: linux
          - os: macos-latest
            script_name: osx
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11

    # Runs a single command using the runners shell
    - name: Run Build on native
      run: ./gradlew --stacktrace native-cli:build
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}

    # Runs a set of commands using the runners shell
    - name: Create Native Image
      run: ./gradlew --stacktrace --debug native-cli:nativeImage
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
    - name: Upload to S3
      run: |
        ./gradlew --stacktrace native-cli:distro
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}

    # Upload the generated artifact
    - name: Upload generated script
      uses: actions/upload-artifact@v2
      with:
        name: dw-${{env.NATIVE_VERSION}}-${{runner.os}}
        path: native-cli/build/distributions/native-cli-${{env.NATIVE_VERSION}}-native-distro-${{ matrix.script_name }}.zip
  # This workflow contains a single job called "build"
